### ISSUE TITLE
ASCII Variable Name Problem

### ISSUE THREAD

**Issue by jimthenerd** [jackyliao123/Java-Algebra-Solver#1]
I understand that the program is trying to find the next ascii character as the new variable name when you add variables, but when the number of variables exceeds 52 (i believe), ascii characters that cannot be typed on a typical keyboard start appearing. 

Suggestion: Add a limit on the number of variables.

**Comment by lolzballs** [comment]
Those characters are added on purpose. "αβγδεζηθικλμ" are greek letters often used in mathematics.

**Comment by lolzballs** [comment]
Also, there is already a limit of 64 characters (52 standard + 12 greek).
